# Netlify Configuration File

[build]
  # Directory to change to before starting a build
  base = "/"
  
  # Directory that contains the deploy-ready HTML files
  publish = "/"
  
  # No build command needed for static site
  command = ""

[build.environment]
  NODE_VERSION = "18"

# Headers for better security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://unpkg.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://api.openweathermap.org https://maps.googleapis.com https://api.twitter.com http://localhost:* http://34.58.110.50:*"

# Enable PWA features
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/javascript"

# Cache static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for API proxy (if needed)
[[redirects]]
  from = "/api/places/*"
  to = "http://34.58.110.50:7077/api/places/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/weather"
  to = "http://34.58.110.50:7077/api/weather"
  status = 200
  force = true

[[redirects]]
  from = "/api/twitter"
  to = "http://34.58.110.50:7077/api/twitter"
  status = 200
  force = true

# SPA routing fallback
[[redirects]]
  from = "/*"
  to = "/index-final.html"
  status = 200

# Environment variables (will be set in Netlify dashboard)
[context.production.environment]
  REACT_APP_API_URL = "http://34.58.110.50:7077"